services:
  - type: web
    name: global-news-tiktok-bot
    env: node
    plan: starter
    buildCommand: npm install --omit=dev
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD
        value: "1"
    healthCheckPath: /
    autoDeploy: true
